### ISSUE TITLE
Does Byfl Support -fopenmp in Clang/LLVM when using v3.9.0?

### ISSUE THREAD

**Issue by nmhamster** [lanl/Byfl#19]
Question for @spakin and @junghans - Does Byfl Support -fopenmp in Clang/LLVM when using v3.9.0?

**Comment by spakin** [comment]
No.  Byfl's support for multithreading is severely broken and needs to be completely replaced.  Sorry about that.

**Comment by nmhamster** [comment]
@spakin thanks for clarification. :-)
