### ISSUE TITLE
Byfl does not work with openmp with -bf-every-bb and -bf-reuse-dist flags.

### ISSUE THREAD

**Issue by AtanuBarai** [lanl/Byfl#27]
```
#include <omp.h>
#include <stdio.h>

#define N 2000

int main ( ) {
  unsigned long i, sum = 0;
  printf("%lu", sum);
#pragma omp parallel for reduction(+:sum)
  for (i = 0; i < N; i++) {
    sum = sum + i;
    printf("%lu", sum);
  }

  /* all threads done */
  printf("Sum is %lu!\n", sum);
  return 0;
}
```

Tried to compile and run the program. But the program stopped with Aborted (core dumped).

Tried these commands:

> bf-clang -fopenmp -bf-every-bb -bf-reuse-dist -o a.out pfunc.c
> ./a.out
> Aborted (core dumped)

I also tried with each flag individually. But the issue remains.

> bf-clang -fopenmp -bf-reuse-dist -o a.out psum.c
> ./a.out
> Aborted (core dumped)

> bf-clang -fopenmp -bf-every-bb -o a.out psum.c 
> ./a.out
> Segmentation fault (core dumped)

I tried with llvm-3.9.0 and llvm-6.0.0. But both failed.

**Comment by spakin** [comment]
Use `-bf-thread-safe`.

Byfl's thread support is pretty awful, but `-bf-thread-safe` at least provides a slim chance of the code not segfaulting.
